### ISSUE TITLE
Provide a task to insert into MySQL

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/plugin-jdbc#124]
### Feature description

There is currently no way to insert into MySQL, only querying is supported.

**Comment by loicmathieu** [comment]
We should be able to leverage the `generateSimpleParameterMetadata` connection properties to implement Batch the same way we did for Postgres.

See https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-connp-props-prepared-statements.html#cj-conn-prop_generateSimpleParameterMetadata

**Comment by tchiotludo** [comment]
done in https://github.com/kestra-io/plugin-jdbc/pull/293
