### ISSUE TITLE
Create a hive jdbc connector

### ISSUE THREAD

**Issue by spljs** [kestra-io/plugin-jdbc#134]
### Feature description

Hello,

I was wondering if it would be possible to add a hive jdbc plugin ? It's still used with some cloud services like AWS EMR. And can be useful for some projects. Have you planned it or need help on this ?

Thanks

**Comment by tchiotludo** [comment]
hey @spljs, 
It's plan but you don't have the bandwidth right now. 
You want to contribute ?

**Comment by loicmathieu** [comment]
I don't know if it's still the case but when I used it a few years ago the Hive JDBC driver has a dependency on Hadoop so it was multiple tens of megabytes.
If it's still the case it would be better to create an Hadoop plugin to avoid doubling the size of this one and maybe later provides more Hadoop task like HDFS which is still used a lot (for Spark for example).

**Comment by spljs** [comment]
I cloud try to implement it if i have the time. We are using aws EMR for one of our project, and maybe we'll not stay on hive or webdfs (hadoop) anyway. Do you have any feedback on those two connectors ? If they are needed by some people it may be interesting to implement it

**Comment by loicmathieu** [comment]
HI @spljs if you're willing to contribute an Hive and maybe an HDFS plugin, we will be happy to incorporate them in Kestra.
We think the best will be to create an Hadoop "group of plugins" for both of them in a dedicated repository.
So if you confirm you plan to contribute it, we'll create a repository and help you get started if you need ;)
