### ISSUE TITLE
Add Athena query and trigger tasks

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-jdbc#147]
### Feature description

Link to the driver: https://docs.aws.amazon.com/athena/latest/ug/connect-with-jdbc.html 

Example JDBC URL: 

```bash
jdbc:awsathena://AwsRegion=[REGION];UID=[ACCESS KEY];PWD=[SECRET KEY];S3OutputLocation=[LOCATION]

# relying on a preconfigured AWS CLI profile:
jdbc:awsathena://AwsRegion=eu-central-1;S3OutputLocation=s3://declarative-orchestration/athena/
```

**Comment by loicmathieu** [comment]
We already have an issue at AWS side for that: https://github.com/kestra-io/plugin-aws/issues/44
