### ISSUE TITLE
Upscale/Downscale ClickHouse resource

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/plugin-jdbc#168]
### Feature description

One user would like to downscale his clickhouse ressource : some flow run only once the 1st of each month, where business users will look to results. They need to have a "big" instance from the 1st to 5th then downscaling

**Comment by anna-geller** [comment]
@Ben8t tagging you to clarify the requirements with LMFR :)

**Comment by Ben8t** [comment]
@anna-geller got some details: in fact it's not related to ClickHouse directly but the underlying cluster provider (Aiven here):
![image](https://github.com/kestra-io/plugin-jdbc/assets/46634684/9a679386-94ec-4a79-9b08-887a95575cd5)
![image](https://github.com/kestra-io/plugin-jdbc/assets/46634684/c6f84199-232c-4be9-8179-77aa0f654e8c)

So it should be more about creating a Aiven plugin to manage ressource there than ClickHouse related things. 
I think we can close that one and open a request for Aiven integration, wdyt ?
