### ISSUE TITLE
Remove not used fetchSize property

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/plugin-jdbc#198]
### Expected Behavior

The fetchSize property is used or we remove it

### Actual Behaviour

Today, all JDBC Query and [Trigger](https://kestra.io/plugins/plugin-jdbc-postgres/triggers/io.kestra.plugin.jdbc.postgresql.trigger#fetchsize) have a fetchSize attribute but none use it.

### Environment Information

- Kestra Version: 0.14-SNAPSHOT
- Plugin version: 
- Operating System (OS / Docker / Kubernetes):
- Java Version (If not docker):

**Comment by anna-geller** [comment]
agree we should remove it if not used

**Comment by loicmathieu** [comment]
`fetchSize` is used (wrong assumption due to Lombok), but not transmitted to all triggers which will be done in #318
