### ISSUE TITLE
[SNOWFLAKE] Add support for multi-statements queries

### ISSUE THREAD

**Issue by brian-mulier-p** [kestra-io/plugin-jdbc#199]
### Feature description

See https://docs.snowflake.com/en/developer-guide/jdbc/jdbc-using#sending-multiple-statements-handling-results: multi-statements are not enabled by default.

I think we can use this `To execute multiple statements without specifying the exact number, pass a value of 0.`

**Comment by anna-geller** [comment]
it will be handled for all JDBC tasks as part of https://github.com/kestra-io/plugin-jdbc/issues/341
