### ISSUE TITLE
Add Truncate option on Oracle Batch task

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/plugin-jdbc#266]
### Feature description

https://kestra.io/plugins/plugin-jdbc-oracle/tasks/io.kestra.plugin.jdbc.oracle.batch

Sometimes you want to truncate the table before inserting. The current solution is to run a Query task with the truncate statement. It could be nice to have an option to truncate the table directly from the insertion task (batch)

Like this for example
![image](https://github.com/kestra-io/plugin-jdbc/assets/46634684/92ac0602-10d0-47a7-b1af-58c898f9a2d4)

**Comment by anna-geller** [comment]
closing as a user can run TRUNCATE TABLE Query before this task to accomplish the same
