### ISSUE TITLE
Adjust all Query tasks and Trigger triggers that use store, fetch, fetchOne, fetchSize to use fetchType instead

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-jdbc#374]
### Feature description

Currently, we do our best to use `fetchType` in all `Query` and `Trigger` implementations: https://kestra.io/plugins/plugin-surrealdb/tasks/io.kestra.plugin.surrealdb.query#fetchtype

However, some older plugins like Postgres use the approach with `store`, `fetch`, `fetchType` and `fetchOne` properties. To keep it maintainable, it seems best to deprecate those and keep the `fetchType` for consistency.

**Comment by mgabelle** [comment]
After taking a quick look I understand that `fetchType` can be STORE, FETCH, FETCH_ONE, or NONE so it is useful to deprecate store, fetch, fetchType, and fetchOne. 
But why do we want to deprecate fetchSize ?

**Comment by Ben8t** [comment]
Indeed `fetchSize` is needed for `fetchType: FETCH`. We should keep it for now.

**Comment by anna-geller** [comment]
thx Ben!
