### ISSUE TITLE
Improve `CopyIn` with Parquet format and ifExists property

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/plugin-jdbc#458]
### Feature description

```  
- id: ingest
    type: io.kestra.plugin.jdbc.postgresql.CopyIn
    format: CSV
    from: "{{ outputs.task.uri }}" # could be a parquet file
    table: schema_a.table_a
```

- Add a new property `ifExists`:

`FAIL` (defaults): raise error (internally we have to check if `schema_a.table_a`)
`REPLACE`: Drop the table before inserting new values, `DROP TABLE IF EXISTS schema_a.table_a` then do classic copy in.
`APPEND`:  insert new values to the existing table, `INSERT INTO ....` - potentially duplicate rows but we don't care.
To check if the table has primary key set ?

- Add support for PARQUET

`format: PARQUET` -> custom code to convert PARQUET to ??? (CSV or BINARY or TEXT, choose the faster one. Probably binary is the best as CSV doesn't handle nested/hierachy data well)

**Comment by anna-geller** [comment]
probably best to first add `format: ION` and then load from ION to Postgres? 

if BINARY is faster, go for it 🚀

**Comment by anna-geller** [comment]
closing for now as it is no longer needed internally
